name: Run Experiments

on:
  workflow_dispatch:  # lets you trigger manually from GitHub
  push:
    branches: [ main ]

jobs:
  experiments:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install scipy networkx

    - name: Run Grover ZNE
      run: python -m qemt.cli run --exp grover_zne

    - name: Run VQE(H₂) optimizer
      run: python -m qemt.cli run --exp vqe_opt

    - name: Run QAOA + DD
      run: python -m qemt.cli run --exp qaoa_dd

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: experiment-results
        path: experiments/results/
